app/Http/routes.php
<?php

// Auth::loginUsingId(3);

Route::group(['middleware' => 'guest'], function() {
    Route::get('/', 'BasicController@index');
    Route::post('login', 'BasicController@login');
    Route::get('register', 'RegisterController@show');
    Route::post('register', 'RegisterController@attempt');
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('logout', 'BasicController@logout');
    Route::resource('group', 'GroupController');

    Route::group(['prefix' => 'group/{group}', 'middleware' => 'group'], function() {
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/{invoice}/clone', 'InvoiceController@showClone')
            ->name('group.{group}.invoice.clone');

        Route::resource('purchase-order', 'PurchaseOrderController');
        Route::resource('price-request', 'PriceRequestController');
        Route::resource('quotation', 'QuotationController');

        Route::resource('product', 'ProductController');
        Route::resource('client', 'ClientController');
        Route::resource('vendor', 'VendorController');
        Route::resource('terms', 'TermsController');

        Route::resource('member', 'MemberController');
        Route::delete('member/{member}/cancel', 'MemberController@cancel')
            ->name('group.{group}.member.cancel');
    });

    Route::group(['prefix' => 'api/{group}', 'middleware' => 'group'], function() {
        Route::get('products', 'ApiController@showProducts');
        Route::get('terms', 'ApiController@showTerms');
    });
});


Route::group(['prefix' => env('ADMIN_PREFIX'), 'namespace' => 'Admin', 'as' => 'admin.'], function() {

    Route::group(['middleware' => 'guest:admin'], function() {
        Route::get('/', 'AuthController@show')->name('auth.show');
        Route::post('login', 'AuthController@login')->name('auth.login');
    });

    Route::group(['middleware' => 'auth:admin'], function() {
        Route::get('logout', 'AuthController@logout')->name('auth.logout');
        Route::get('dashboard', 'DashboardController@show')->name('dashboard');
        Route::resource('user', 'UserController');
        Route::delete('user/{user}/ban', 'UserController@ban')->name('admin.user.ban');
        Route::resource('admin', 'AdminController');
        Route::get('settings', 'AuthController@showSettings')->name('settings.show');
        Route::post('settings', 'AuthController@storeSettings')->name('settings.store');
    });
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = ['owner_id', 'group_id', 'name'];

    public function owner()
    {
        return $this->belongsTo(User::class);
    }

    public function members()
    {
        return $this->hasMany(GroupMember::class);
    }

    public function pending()
    {
        return $this->hasMany(Invitation::class);
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\GroupMember;
use App\Group;
use App\Action;
use Auth;

class GroupController extends Controller
{
    public function index()
    {
        $groups = GroupMember::with('group')
            ->where('user_id', Auth::id())
            ->orderBy('created_at', 'desc')
            ->get();

        return view('group.index', [
            'groups' => $groups
        ]);
    }

    public function create()
    {
        return view('group.create');
    }

    public function show($id)
    {
        $group = Group::whereHas('members', function($query) {
            $query->where('user_id', Auth::id());
        })
        ->where('id', $id)
        ->first();

        $actions = Action::where('group_id', $group->id)
            ->orderBy('created_at', 'desc')
            ->limit(20)
            ->get();

        return view('group.show', [
            'group' => $group,
            'actions' => $actions
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $group = Group::create([
            'owner_id' => Auth::id(),
            'name' => $request->name
        ]);

        GroupMember::create([
            'user_id' => Auth::id(),
            'group_id' => $group->id
        ]);

        return redirect()
            ->route('group.index')
            ->withMessage('Successfully created group!');
    }
}

resources/views/group/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <div class="box-heading">
                    <p class="box-title">Groups</p>
                    <a href="{{route('group.index')}}" class="btn btn-default box-btn">Back</a>
                </div>
                <div class="box-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form class="row" action="{{route('group.store')}}" method="post">
                        {{csrf_field()}}
                        <div class="col-sm-4 col-sm-offset-4">
                            <div class="form-group">
                                <label>Group Name</label>
                                <input type="text" class="form-control" name="name" value="{{old('name')}}">
                            </div>
                        </div>
                        <div class="col-sm-4 col-sm-offset-4">
                            <input type="submit" value="CREATE" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/group/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="box">
        <div class="box-heading">
            <p class="box-title">Groups</p>
            <a href="{{route('group.create')}}" class="btn btn-success box-btn">Create new</a>
        </div>
        <div class="box-body">
            <div class="row">
                @foreach($groups as $group)
                    <div class="col-sm-3">
                        <div class="group-item">
                            <a class="group-title" href="{{route('group.show', $group->group)}}">
                                {{$group->group->name}}
                            </a>
                            <div class="group-head clearfix">
                                <small class="pull-left">{{$group->group->members->count()}} Members</small>
                                @if($group->group->owner_id == $group->user_id)
                                    <span class="pull-right label label-success" title="Your are the owner">You</span>
                                @else
                                    <span class="pull-right label label-primary" title="{{$group->group->owner->name}} is the owner">{{$group->group->owner->name}}</span>
                                @endif
                            </div>

                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@stop

resources/views/group/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="box">
        <div class="box-heading">
            <p class="box-title">Groups</p>
            <p class="box-btn">
                <span class="box-title">
                    {{$group->name}}
                    @if($group->owner_id == Auth::id())
                        <small class="label label-success">You</small>
                    @else
                        <small class="label label-primary">{{$group->owner->name}}</small>
                    @endif
                </span>
            </span>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-sm-3">
                    <div class="dash-box">
                        <h1>{{App\Product::inGroup($group->id)->count()}}</h1>
                        <p>Products</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="dash-box">
                        <h1>{{App\Client::inGroup($group->id)->count()}}</h1>
                        <p>Client</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="dash-box">
                        <h1>{{App\Vendor::inGroup($group->id)->count()}}</h1>
                        <p>Vendors</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="dash-box">
                        <h1>{{App\GroupMember::inGroup($group->id)->count()}}</h1>
                        <p>Members</p>
                    </div>
                </div>
            </div>
            <h4>Group Log</h4>
            <table class="table table-striped">
                <tbody>
                    @foreach($actions as $action)
                        <tr>
                            <td>
                                <span>{{$action->user->name}} {{$action->description}}</span>
                                <span class="pull-right">{{$action->created_at->diffForHumans()}}</span>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop