app/Http/routes.php
<?php

// Auth::loginUsingId(3);

Route::group(['middleware' => 'guest'], function() {
    Route::get('/', 'BasicController@index');
    Route::post('login', 'BasicController@login');
    Route::get('register', 'RegisterController@show');
    Route::post('register', 'RegisterController@attempt');
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('logout', 'BasicController@logout');
    Route::resource('group', 'GroupController');

    Route::group(['prefix' => 'group/{group}', 'middleware' => 'group'], function() {
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/{invoice}/clone', 'InvoiceController@showClone')
            ->name('group.{group}.invoice.clone');

        Route::resource('purchase-order', 'PurchaseOrderController');
        Route::resource('price-request', 'PriceRequestController');
        Route::resource('quotation', 'QuotationController');

        Route::resource('product', 'ProductController');
        Route::resource('client', 'ClientController');
        Route::resource('vendor', 'VendorController');
        Route::resource('terms', 'TermsController');

        Route::resource('member', 'MemberController');
        Route::delete('member/{member}/cancel', 'MemberController@cancel')
            ->name('group.{group}.member.cancel');
    });

    Route::group(['prefix' => 'api/{group}', 'middleware' => 'group'], function() {
        Route::get('products', 'ApiController@showProducts');
        Route::get('terms', 'ApiController@showTerms');
    });
});


Route::group(['prefix' => env('ADMIN_PREFIX'), 'namespace' => 'Admin', 'as' => 'admin.'], function() {

    Route::group(['middleware' => 'guest:admin'], function() {
        Route::get('/', 'AuthController@show')->name('auth.show');
        Route::post('login', 'AuthController@login')->name('auth.login');
    });

    Route::group(['middleware' => 'auth:admin'], function() {
        Route::get('logout', 'AuthController@logout')->name('auth.logout');
        Route::get('dashboard', 'DashboardController@show')->name('dashboard');
        Route::resource('user', 'UserController');
        Route::delete('user/{user}/ban', 'UserController@ban')->name('admin.user.ban');
        Route::resource('admin', 'AdminController');
        Route::get('settings', 'AuthController@showSettings')->name('settings.show');
        Route::post('settings', 'AuthController@storeSettings')->name('settings.store');
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Office Admin</title>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
    <meta name="viewport" content="initial-scale=1.0">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{route('admin.dashboard')}}">Admin</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Hi, {{Auth::guard('admin')->user()->name}}</a></li>
                    <li><a href="{{route('admin.auth.logout')}}">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                <div class="sidebar">
                    <ul>
                        @foreach(Config::get('menu.admin') as $item)
                            <li>
                                @if($item[0] == 'break')
                                    <span class="sidebar-break"></span>
                                @else
                                <a href="{{route($item[1])}}">
                                    {{$item[0]}}
                                    <span class="glyphicon glyphicon-circle-arrow-right">
                                </a>
                                @endif
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
            <div class="col-sm-10">
                @if(session()->has('message'))
                    <div class="alert alert-info">
                        {{session()->get('message')}}
                    </div>
                @endif
                @if(session()->has('error'))
                    <div class="alert alert-danger">
                        {{session()->get('error')}}
                    </div>
                @endif
                @if(session()->has('warning'))
                    <div class="alert alert-warning">
                        {{session()->get('warning')}}
                    </div>
                @endif

                @yield('content')
            </div>
    </div>
    @yield('scripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Office</title>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
    <meta name="viewport" content="initial-scale=1.0">
</head>
<body>
    @include('layouts.nav')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                @include('layouts.sidebar')
            </div>
            <div class="col-sm-10">
                @if(session()->has('message'))
                    <div class="alert alert-info">
                        {{session()->get('message')}}
                    </div>
                @endif
                @if(session()->has('error'))
                    <div class="alert alert-danger">
                        {{session()->get('error')}}
                    </div>
                @endif
                @if(session()->has('warning'))
                    <div class="alert alert-warning">
                        {{session()->get('warning')}}
                    </div>
                @endif

                @yield('content')
            </div>
    </div>
    @yield('scripts')
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Office</title>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
    <meta name="viewport" content="initial-scale=1.0">
</head>
<body>
    @include('layouts.nav')
    <div class="container-fluid">
        @if(session()->has('message'))
            <div class="alert alert-info">
                {{session()->get('message')}}
            </div>
        @endif
        @if(session()->has('error'))
            <div class="alert alert-danger">
                {{session()->get('error')}}
            </div>
        @endif
        @if(session()->has('warning'))
            <div class="alert alert-warning">
                {{session()->get('warning')}}
            </div>
        @endif
        @yield('content')
    </div>
    @yield('scripts')
</body>
</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/group">Office</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{route('group.index')}}">My Groups</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Hi, {{Auth::user()->name}}</a></li>
                <li><a href="/logout">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/public.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Office</title>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
    <meta name="viewport" content="initial-scale=1.0">
</head>
<body>
    <div class="container-fluid">
        @yield('content')
    </div>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="sidebar">
    <ul>
        @foreach(Config::get('menu.app') as $item)
            <li>
                @if($item[0] == 'break')
                    <span class="sidebar-break"></span>
                @else
                <a href="{{route($item[1], $group)}}">
                    {{$item[0]}}
                    <span class="glyphicon glyphicon-circle-arrow-right">
                </a>
                @endif
            </li>
        @endforeach
    </ul>
</div>