app/Http/routes.php
<?php

// Auth::loginUsingId(3);

Route::group(['middleware' => 'guest'], function() {
    Route::get('/', 'BasicController@index');
    Route::post('login', 'BasicController@login');
    Route::get('register', 'RegisterController@show');
    Route::post('register', 'RegisterController@attempt');
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('logout', 'BasicController@logout');
    Route::resource('group', 'GroupController');

    Route::group(['prefix' => 'group/{group}', 'middleware' => 'group'], function() {
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/{invoice}/clone', 'InvoiceController@showClone')
            ->name('group.{group}.invoice.clone');

        Route::resource('purchase-order', 'PurchaseOrderController');
        Route::resource('price-request', 'PriceRequestController');
        Route::resource('quotation', 'QuotationController');

        Route::resource('product', 'ProductController');
        Route::resource('client', 'ClientController');
        Route::resource('vendor', 'VendorController');
        Route::resource('terms', 'TermsController');

        Route::resource('member', 'MemberController');
        Route::delete('member/{member}/cancel', 'MemberController@cancel')
            ->name('group.{group}.member.cancel');
    });

    Route::group(['prefix' => 'api/{group}', 'middleware' => 'group'], function() {
        Route::get('products', 'ApiController@showProducts');
        Route::get('terms', 'ApiController@showTerms');
    });
});


Route::group(['prefix' => env('ADMIN_PREFIX'), 'namespace' => 'Admin', 'as' => 'admin.'], function() {

    Route::group(['middleware' => 'guest:admin'], function() {
        Route::get('/', 'AuthController@show')->name('auth.show');
        Route::post('login', 'AuthController@login')->name('auth.login');
    });

    Route::group(['middleware' => 'auth:admin'], function() {
        Route::get('logout', 'AuthController@logout')->name('auth.logout');
        Route::get('dashboard', 'DashboardController@show')->name('dashboard');
        Route::resource('user', 'UserController');
        Route::delete('user/{user}/ban', 'UserController@ban')->name('admin.user.ban');
        Route::resource('admin', 'AdminController');
        Route::get('settings', 'AuthController@showSettings')->name('settings.show');
        Route::post('settings', 'AuthController@storeSettings')->name('settings.store');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function groups()
    {
        return $this->hasMany(GroupMember::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use App\Invitation;
use Mail;

class UserController extends Controller
{
    public function index()
    {
        $users = User::orderBy('created_at', 'desc')
            ->get();
        return view('admin.user.index', [
            'users' => $users
        ]);
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email|unique:users',
            'user_type' => 'required|in:1,2'
        ]);

        $invite = Invitation::where('email', $request->email)
            ->first();

        if($invite) {
            return redirect()
                ->route('admin.admin.user.index')
                ->withWarning('Invitation already send!');
        }

        //generate token
        $token = str_random(128);

        while (Invitation::whereToken($token)->first()) {
            $token = str_random(128);
        }

        // invite to join app
        $invitation = Invitation::create([
            'email' => $request->email,
            'token' => $token,
            'user_type' => $request->user_type
        ]);

        Mail::queue('emails.invite', ['invitation' => $invitation], function ($m) use ($invitation) {
            $m->from('sandbox@sparkpostbox.com', 'Your Application');

            $m->to($invitation->email)->subject('Invitation to join');
        });

        return redirect()
            ->route('admin.admin.user.index')
            ->withMessage('Successfully send Invitation!');
    }

    public function ban(User $user)
    {
        if($user->is_banned) {
            $user->is_banned = 0;
        } else {
            $user->is_banned = 1;
        }

        $user->save();

        return redirect()
            ->route('admin.admin.user.index')
            ->withMessage('Successfully banned user!');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box">
        <div class="box-heading">
            <p class="box-title">Send Invitation</p>
            <a href="{{route('admin.admin.user.index')}}" class="btn btn-default box-btn">Back</a>
        </div>
        <div class="box-body">
            @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="row" action="{{route('admin.admin.user.store')}}" method="post">
                {{csrf_field()}}
                <div class="col-sm-4 col-sm-offset-4">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" name="email" value="{{old('email')}}">
                    </div>
                    <div class="form-group">
                        <label>User Type</label>
                        <select class="form-control" name="user_type">
                            <option>Select</option>
                            <option value="1">Regular</option>
                            <option value="2">Basic</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-4 col-sm-offset-4">
                    <input type="submit" value="SEND" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
@stop

@section('scripts')
@stop

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box">
        <div class="box-heading">
            <p class="box-title">Users</p>
            <a href="{{route('admin.admin.user.create')}}" class="btn btn-success box-btn">Create new</a>
        </div>
        <div class="box-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Type</th>
                        <th colspan="2">Created At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>
                                @if($user->type == 1)
                                    <span class="label label-success">Regular</span>
                                @else
                                    <span class="label label-info">Basic</span>
                                @endif
                            </td>
                            <td>
                                @if($user->is_banned)
                                    <span class="label label-danger">Banned</span>
                                @else
                                    <span class="label label-success">Active</span>
                                @endif
                            </td>
                            <td>{{$user->created_at}}</td>
                            <td>
                                <a href="{{route('admin.admin.user.show', [$user])}}" class="btn btn-default btn-sm">View</a>
                                <form class="form-inline" action="{{route('admin.admin.user.ban', [$user])}}" method="post">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="DELETE">
                                    @if($user->is_banned)
                                        <input type="submit" value="Un-Ban" class="btn btn-warning btn-sm">
                                    @else
                                        <input type="submit" value="Ban" class="btn btn-warning btn-sm">
                                    @endif
                                </form>
                                <form class="form-inline" action="{{route('admin.admin.user.destroy', [$user])}}" method="post">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop